name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  checks: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  build:
    needs: test
    uses: Narazaka/vpm-repos/.github/workflows/release.yml@main
    with:
      novcc: false
