name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  checks: write

jobs:
  web-test:
    uses: ./.github/workflows/web-test.yml

  unity-test:
    uses: ./.github/workflows/unity-test.yml
    permissions:
      checks: write
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

  build:
    needs: [web-test]
    uses: Narazaka/vpm-repos/.github/workflows/release.yml@main
    with:
      novcc: false
      exclude: |
        Tests
        Tests.meta
