name: Test

on:
  push: {}
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  web-test:
    uses: ./.github/workflows/web-test.yml

  unity-test:
    uses: ./.github/workflows/unity-test.yml
    permissions:
      checks: write
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
