name: Web Test

on:
  workflow_call: {}

jobs:
  web-test:
    name: Web Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: generator~/pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
        working-directory: ./generator~
      - run: pnpm run check
        working-directory: ./generator~
      - run: pnpm run build
        working-directory: ./generator~
      - run: pnpm test
        working-directory: ./generator~
      - run: pnpm exec playwright install chromium
        working-directory: ./generator~
      - run: pnpm run e2e
        working-directory: ./generator~
